### ISSUE TITLE
Date format is inconsistent 

### ISSUE THREAD

**Issue by gianlucadonato** [NeokingdomDAO/odoo#14]
# Current Behaviour
<img width="373" alt="Screenshot 2023-04-04 at 15 49 24" src="https://user-images.githubusercontent.com/1878447/229814337-39a671c5-80be-4fb8-8786-cf52883d8599.png">

Date fields used to have the same format, but now it seems there are different timestamps to represent a date.
Form example the tasks `date_deadline` field has 6 digits, `write_date` has 16 digits with dot notation, and start and end dates have 9 digits. So it's very confusing on how to covert these dates.

# Expected Behaviour 

All the Date fields should have the same format.

**Comment by PeterSchwarzHPI** [comment]
As far as I understand the graphql api distinguishes between date and date time. That being said: it might be confusing that it says "write_date" however this is something being wrong in the odoo standard. write_date is a date time whereas date_deadline really is just a date.

Also I cannot confirm that start and end only have 9 digits (but 12). When you now compare write_date with start you will realise that start does not track seconds (we decided on that) whereas write_date does which is why write_date does have a point notation.

I think with this clarification the issue is solved.

**Comment by gianlucadonato** [comment]
Is there a way to query odoo in a way that returns the dates in the same format?
